export const SITE_COPY_SEED = [
  {
    key: "what-we-do",
    value: {
      eyebrow: "What we do",
      titleLines: ["One shoot.", "Every channel.", "One studio."],
      body: "ESTATEDATA.CLOUD combines creative media production with advanced reality capture technology — photography, cinematic video, drone, AI media, Matterport 3D tours and Scan-to-BIM — so your property communicates its full value before anyone steps inside.",
      primaryCta: "Start a Project",
      primaryCtaHref: "/#quote",
      secondaryCta: "See Services",
      secondaryCtaHref: "/#photography",
      reelLabel: "Watch the reel",
      reelUrl: "/__l5e/assets-v1/77e53f23-6cc4-45aa-99c1-a08109bbb34c/promo.mp4",
      reelPosterUrl: "/assets/hero-villa-BcD5T4f7.webp",
    },
  },
  {
    key: "web-pages",
    value: {
      eyebrow: "Property websites",
      title: "A Web Page Built to Sell One Property.",
      body: "A dedicated, high-converting property website that brings every asset we produce — photos, video, drone, 3D tour and floor plans — into one branded experience you can share with a single link.",
      ctaLabel: "Build My Property Page",
      href: "/web-pages",
      startingPrice: "$399",
      includedLabel: "What's included",
      included: [
        "Custom single-property website",
        "Mobile-first responsive design",
        "Hero video or cinematic gallery",
        "Embedded Matterport 3D tour",
        "Floor plans & downloadable brochure",
        "Lead capture form & instant notifications",
        "Agent branding or unbranded MLS version",
        "Custom domain setup",
        "SEO & social share previews",
        "Analytics and visitor tracking",
        "Hosting & maintenance",
        "48-hour turnaround",
      ],
      pricing: [
        { label: "Single Property Web Page", price: "from $399" },
        { label: "Premium Page (video hero + 3D tour)", price: "from $649" },
        { label: "Agent / Brokerage Site", price: "from $1,499" },
        { label: "Development & Multifamily", price: "Custom Quote" },
        { label: "Hosting & domain", price: "$19 / month" },
      ],
    },
  },
  {
    key: "contact",
    value: {
      eyebrow: "Book a shoot",
      title: "Let's create something great.",
      body: "Name, contact, the service you need, and a short note are enough. Property details are optional.",
      phoneLabel: "(310) 555-0142",
      phoneHref: "tel:+13105550142",
      emailLabel: "studio@estatedata.cloud",
      emailHref: "mailto:studio@estatedata.cloud",
      hours: "Mon – Sat · 7:00 AM – 8:00 PM PT",
      address: "Los Angeles & surrounding areas",
      social: [
        { label: "Instagram", href: "https://instagram.com/" },
        { label: "LinkedIn", href: "https://linkedin.com/" },
        { label: "YouTube", href: "https://youtube.com/" },
        { label: "Vimeo", href: "https://vimeo.com/" },
      ],
    },
  },
] as const;
