import type { PricingPackage } from "@/features/pricing/content/pricingPackageTypes";

export const PRICING_MEDIA_PACKAGES_COPY = {
  sectionTitle: "Choose how far you want to go.",
  priceSuffix: "",
  packages: [
    {
      id: "essential",
      name: "Essential",
      price: "$349",
      cardAccent: "blue",
      features: [
        "Professional photography",
        "Interior & exterior",
        "Professional editing",
        "20+ final images",
      ],
      bookLabel: "Book Essential",
      bookHref: "/#contact",
    },
    {
      id: "digital",
      name: "Digital",
      price: "$499",
      cardAccent: "purple",
      features: [
        "Professional photography",
        "3D Matterport tour",
        "Professional editing",
        "Digital floor plan",
      ],
      bookLabel: "Book Digital",
      bookHref: "/#contact",
    },
    {
      id: "cinematic",
      name: "Cinematic",
      price: "$799",
      cardAccent: "orange",
      features: [
        "Professional photography",
        "Cinematic property video",
        "Drone photography",
        "Professional editing",
        "Social media version",
      ],
      bookLabel: "Book Cinematic",
      bookHref: "/#contact",
    },
    {
      id: "complete",
      name: "Complete",
      price: "$999",
      cardAccent: "purple",
      highlighted: true,
      badgeLabel: "Most complete",
      features: [
        "Professional photography",
        "Cinematic 4K video",
        "Drone photography",
        "Drone video",
        "Matterport 3D tour",
        "Floor plan",
        "Social media vertical video",
        "Professional editing",
      ],
      bookLabel: "Book Complete",
      bookHref: "/#contact",
    },
    {
      id: "luxury-development",
      name: "Luxury / Development",
      price: "Custom",
      cardAccent: "orange",
      features: [
        "Custom production planning",
        "Dedicated creative direction",
        "Multi-day capture",
        "Luxury estates",
        "Commercial properties",
        "New developments",
        "Hotels & multifamily",
        "Architectural projects",
      ],
      bookLabel: "Request Custom Proposal",
      bookHref: "/#contact",
    },
  ] as const satisfies readonly PricingPackage[],
} as const;
